application: tack-it
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

handlers:
- url: /static_dir
  static_dir: static_dir
  
- url: /static_dir/pictures
  static_dir: pictures
  
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest